let
    baseUrl = "https://api.exactspotter.com/v3/LeadsSold" // Aqui você irá adicionar o endpoint segundo a documentação da Exact Sales
    token = "@@@@@@@@@@@@@@@@@", // Aqui você irá adicionar seu token
    pageSize = 500,
    totalRecords = 1000, // Aqui você irá adicionar o número de requisições totais desejadas. Por exemplo, se você quiser obter 1000 registros no total
    numberOfPages = Number.RoundUp(totalRecords / pageSize),
    allRecords = List.Generate(
        () => [Page = 0, Result = {}],
        each [Page] < numberOfPages,
        each [Page = [Page] + 1, Result = Json.Document(Web.Contents(baseUrl & "?$skip=" & Text.From([Page] * pageSize), [Headers=[#"Content-Type"="application/json", token_exact=token]]))],
        each [Result]
    ),
    combinedData = Table.FromList(allRecords, Splitter.SplitByNothing()),
    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(combinedData, [PromoteAllScalars=true]),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Column1", type any}})
in
    #"Tipo Alterado"
